default_install_hook_types:
  - pre-commit
  # For the commitizen check
  - commit-msg
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.18.3
    hooks:
      # Check all commits on the current branch that are not yet
      # merged on main
      - id: commitizen-branch
        # Fix an issue with the default way to detect commits
        # on the current branch
        # https://github.com/commitizen-tools/commitizen/issues/704
        args: ["--rev-range", "origin/main..HEAD"]
      # Check the current commit
      - id: commitizen
