default_install_hook_types:
  - pre-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        # Allow !reference tags in .gitlab-ci.yml
        # https://github.com/pre-commit/pre-commit-hooks/issues/701
        args: ['--unsafe']
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/djlint/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-jinja
      - id: djlint-reformat-jinja
  - repo: local
    hooks:
      # This hook would need to be run inside a docker
      # container or somewhere with access to the database.
      # Due to time constraints, we haven't implemented
      # that at the moment.
      # We're only running this in the CI via tox.ini
      # instead.
      # - id: missing-migrations
      #   name: Check missing Django migrations
      #   description: This hook checks if changes has been made to models but not reflected into a migration.
      #   entry: ./manage makemigrations
      #   args: [--check, --dry-run, --no-input]
      #   language: system
      #   types_or: [python, directory]
      #   files: "models"
      #   require_serial: true
      #   pass_filenames: false
      - id: outdated-translations
        name: Check for outdated .PO files
        description: This hook checks if the automatically generated .PO files need updating.
        entry: make update-translations
        language: system
        types_or: [jinja, python, directory, pofile]
        require_serial: true
        pass_filenames: false
