# This configuration is not meant for production use.

services:
  database:
    image: postgis/postgis:15-3.4-alpine
    env_file: [docker/env]
    restart: always
    volumes:
      - turtlemail-db:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      start_period: 20s
      timeout: 5s
      retries: 5

  backend:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      database:
        condition: service_healthy
    env_file: [docker/env]
    volumes:
      - turtlemail-data:/var/lib/turtlemail
      - ./turtlemail_settings.py:/etc/turtlemail/turtlemail_settings.py

  worker:
    build:
      dockerfile: Dockerfile
      context: .
    env_file: [docker/env]
    volumes:
      - turtlemail-data:/var/lib/turtlemail
      - ./turtlemail_settings.py:/etc/turtlemail/turtlemail_settings.py
    command: "huey"
    depends_on: [backend]

  nginx:
    image: nginx
    depends_on: [backend]
    volumes:
      - ./docker/nginx-server.conf:/etc/nginx/nginx.conf
      - ./docker/nginx-app.conf:/etc/nginx/snippets/app.conf
    ports: ["8637:8637"]

volumes:
  turtlemail-data:
  turtlemail-db:
