# Generated by Django 4.2.11 on 2024-04-03 14:02

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("turtlemail", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("is_home", models.BooleanField(verbose_name="Home")),
                (
                    "lat",
                    models.DecimalField(
                        decimal_places=15, max_digits=17, verbose_name="Latitude"
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        decimal_places=15, max_digits=17, verbose_name="Longitude"
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.CreateModel(
            name="Stay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("SOMETIMES", "Sometimes"),
                            ("ONCE", "Once"),
                        ],
                        max_length=10,
                        verbose_name="Frequency",
                    ),
                ),
                (
                    "start",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=datetime.date.today
                            )
                        ],
                        verbose_name="Start",
                    ),
                ),
                (
                    "end",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=datetime.date.today
                            )
                        ],
                        verbose_name="End",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="turtlemail.location",
                        verbose_name="Location",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stay",
                "verbose_name_plural": "Stays",
            },
        ),
    ]
