# Generated by Django 4.2.11 on 2024-04-09 14:41

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("turtlemail", "0003_add_user_to_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Packet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("human_id", models.TextField(unique=True, verbose_name="Code")),
            ],
            options={
                "verbose_name": "Packet",
                "verbose_name_plural": "Packets",
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[("CURRENT", "Current"), ("CURRENT", "Cancelled")],
                        verbose_name="Status",
                    ),
                ),
                (
                    "packet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_routes",
                        to="turtlemail.packet",
                        verbose_name="Packet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
            },
        ),
        migrations.CreateModel(
            name="RouteStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=datetime.date.today
                            )
                        ],
                        verbose_name="Start",
                    ),
                ),
                (
                    "end",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=datetime.date.today
                            )
                        ],
                        verbose_name="End",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("SUGGESTED", "Suggested"),
                            ("ACCEPTED", "Accepted"),
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        verbose_name="Status",
                    ),
                ),
                (
                    "next_step",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="turtlemail.routestep",
                        verbose_name="Next Step",
                    ),
                ),
                (
                    "packet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="turtlemail.packet",
                        verbose_name="Packet",
                    ),
                ),
                (
                    "previous_step",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="turtlemail.routestep",
                        verbose_name="Previous Step",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="turtlemail.route",
                        verbose_name="Route",
                    ),
                ),
                (
                    "stay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="route_steps",
                        to="turtlemail.stay",
                        verbose_name="Stay",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="packet",
            name="current_route",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="turtlemail.route",
                verbose_name="Current route",
            ),
        ),
        migrations.AddField(
            model_name="packet",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="received_packets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Recipient",
            ),
        ),
        migrations.AddField(
            model_name="packet",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sent_packets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sender",
            ),
        ),
        migrations.CreateModel(
            name="DeliveryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="Datetime")),
                (
                    "action",
                    models.TextField(
                        choices=[
                            ("ROUTE_STEP_CHANGE", "Route Step Changed"),
                            ("NEW_ROUTE", "New Route"),
                        ],
                        verbose_name="Action Choices",
                    ),
                ),
                (
                    "new_step_status",
                    models.TextField(
                        choices=[
                            ("SUGGESTED", "Suggested"),
                            ("ACCEPTED", "Accepted"),
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        null=True,
                        verbose_name="New Route Step Status",
                    ),
                ),
                (
                    "packet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="turtlemail.packet",
                        verbose_name="Packet",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="turtlemail.route",
                        verbose_name="Route",
                    ),
                ),
                (
                    "route_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_logs",
                        to="turtlemail.routestep",
                        verbose_name="Route Step",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="packet",
            index=models.Index(
                fields=["human_id"], name="turtlemail__human_i_3b0019_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packet",
            index=models.Index(
                fields=["sender_id"], name="turtlemail__sender__4a250b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packet",
            index=models.Index(
                fields=["receiver_id"], name="turtlemail__receive_20cca5_idx"
            ),
        ),
    ]
