# Generated by Django 4.2.11 on 2024-04-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("turtlemail", "0004_packet_route_routestep_packet_current_route_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliverylog",
            options={
                "verbose_name": "Delivery Log Entry",
                "verbose_name_plural": "Delivery Log Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="routestep",
            options={
                "verbose_name": "Route Step",
                "verbose_name_plural": "Route Steps",
            },
        ),
        migrations.RemoveField(
            model_name="packet",
            name="current_route",
        ),
        migrations.AlterField(
            model_name="route",
            name="status",
            field=models.TextField(
                choices=[("CURRENT", "Current"), ("CANCELLED", "Cancelled")],
                verbose_name="Status",
            ),
        ),
    ]
