# Generated by Django 4.2.11 on 2024-04-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "turtlemail",
            "0005_alter_deliverylog_options_alter_routestep_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="packet",
            name="turtlemail__receive_20cca5_idx",
        ),
        migrations.RenameField(
            model_name="packet",
            old_name="receiver",
            new_name="recipient",
        ),
        migrations.AddIndex(
            model_name="packet",
            index=models.Index(
                fields=["recipient_id"], name="turtlemail__recipie_582c49_idx"
            ),
        ),
    ]
