# Generated by Django 4.2.11 on 2024-04-18 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("turtlemail", "0006_remove_packet_turtlemail__receive_20cca5_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="packet",
            options={"verbose_name": "Delivery", "verbose_name_plural": "Deliveries"},
        ),
        migrations.AlterField(
            model_name="deliverylog",
            name="packet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="turtlemail.packet",
                verbose_name="Delivery",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="packet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_routes",
                to="turtlemail.packet",
                verbose_name="Delivery",
            ),
        ),
        migrations.AlterField(
            model_name="routestep",
            name="packet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="turtlemail.packet",
                verbose_name="Delivery",
            ),
        ),
    ]
