# Generated by Django 4.2.11 on 2024-04-25 13:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("turtlemail", "0007_alter_packet_options_alter_deliverylog_packet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, null=True, srid=4326, verbose_name="Location"
            ),
        ),
        migrations.RunSQL(
            "UPDATE turtlemail_location SET point = POINT(lon, lat)::GEOMETRY"
            # No reverse snippet as I don't think we're at a stage where we need that
        ),
        migrations.AlterField(
            model_name="location",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, srid=4326, verbose_name="Location"
            ),
        ),
        migrations.RemoveField(
            model_name="location",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="location",
            name="lon",
        ),
    ]
