# Generated by Django 4.2.13 on 2024-05-20 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import turtlemail.models


class Migration(migrations.Migration):
    dependencies = [
        ("turtlemail", "0008_remove_location_lat_remove_location_lon_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "unique": "This user has already been invited."
                        },
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "token",
                    models.TextField(default=turtlemail.models.default_invite_token),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["token"], name="turtlemail__token_14ce37_idx")
                ],
            },
        ),
    ]
