# Generated by Django 4.2.13 on 2024-05-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("turtlemail", "0010_stay_inactive_until_alter_deliverylog_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverylog",
            name="action",
            field=models.TextField(
                choices=[
                    ("ROUTE_STEP_CHANGE", "Travel Step Changed"),
                    ("SEARCHING_ROUTE", "Updating Travel Plans"),
                    ("NEW_ROUTE", "Travel Plans Changed"),
                    ("NO_ROUTE_FOUND", "Unable to find Travel Plans"),
                ],
                verbose_name="Action Choices",
            ),
        ),
    ]
