# Generated by Django 4.2.13 on 2024-05-28 15:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("turtlemail", "0011_alter_deliverylog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stay",
            name="inactive_until",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date.today
                    )
                ],
                verbose_name="Inactive until",
            ),
        ),
    ]
