# Generated by Django 4.2.13 on 2024-05-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("turtlemail", "0012_alter_stay_inactive_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="stay",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
