# Generated by Django 4.2.13 on 2024-06-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("turtlemail", "0014_alter_routestep_options_alter_deliverylog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverylog",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Human readable log entry"
            ),
        ),
        migrations.AlterField(
            model_name="deliverylog",
            name="action",
            field=models.TextField(
                choices=[
                    ("ROUTE_STEP_CHANGE", "User's journey changed"),
                    ("SEARCHING_ROUTE", "Making new travel plans"),
                    ("NEW_ROUTE", "Found new travel plans"),
                    ("NO_ROUTE_FOUND", "Unable to find travel plans"),
                    ("PACKET_CHANGED_LOCATION", "Packet arrived at new location"),
                ],
                verbose_name="Action Choices",
            ),
        ),
    ]
