# Generated by Django 4.2.13 on 2024-06-26 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("turtlemail", "0015_deliverylog_description_alter_deliverylog_action"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invite",
            options={"ordering": ["-accepted_at", "-created_at"]},
        ),
        migrations.AddField(
            model_name="invite",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invite",
            name="created_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_invite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invite",
            name="dismissed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="invite",
            name="invited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
