# Generated by Django 4.2.13 on 2024-06-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("turtlemail", "0015_deliverylog_description_alter_deliverylog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
