# Generated by Django 4.2.13 on 2024-06-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("turtlemail", "0016_location_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="is_home",
            field=models.BooleanField(default=False, verbose_name="Home"),
        ),
    ]
