# Generated by Django 4.2.13 on 2024-07-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turtlemail', '0016_chatmessage_systemchatmessage_userchatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['route_step', 'created_at'], 'verbose_name': 'Chat message', 'verbose_name_plural': 'Chat messages'},
        ),
    ]
