# Generated by Django 4.2.13 on 2024-07-08 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("turtlemail", "0017_alter_location_is_home"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Datetime"),
                ),
                ("content", models.TextField(verbose_name="Message content")),
                (
                    "status",
                    models.CharField(
                        choices=[("N", "new"), ("R", "received")],
                        default="N",
                        max_length=2,
                        verbose_name="Status",
                    ),
                ),
                (
                    "route_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="turtlemail.routestep",
                        verbose_name="RouteStep context",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat message",
                "verbose_name_plural": "Chat messages",
                "ordering": ["route_step", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemChatMessage",
            fields=[
                (
                    "chatmessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="turtlemail.chatmessage",
                    ),
                ),
            ],
            bases=("turtlemail.chatmessage",),
        ),
        migrations.CreateModel(
            name="UserChatMessage",
            fields=[
                (
                    "chatmessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="turtlemail.chatmessage",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Message author",
                    ),
                ),
            ],
            bases=("turtlemail.chatmessage",),
        ),
    ]
