# Generated by Django 4.2.13 on 2024-07-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("turtlemail", "0017_alter_location_is_home"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="routestep",
            options={
                "ordering": ["start", "end"],
                "verbose_name": "Route Step",
                "verbose_name_plural": "Route Steps",
            },
        ),
        migrations.AlterField(
            model_name="deliverylog",
            name="new_step_status",
            field=models.TextField(
                choices=[
                    ("SUGGESTED", "Suggested"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("ONGOING", "Ongoing"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("REPORTED_PROBLEM", "Problem reported"),
                ],
                null=True,
                verbose_name="New Route Step Status",
            ),
        ),
        migrations.AlterField(
            model_name="routestep",
            name="status",
            field=models.TextField(
                choices=[
                    ("SUGGESTED", "Suggested"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("ONGOING", "Ongoing"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("REPORTED_PROBLEM", "Problem reported"),
                ],
                verbose_name="Status",
            ),
        ),
        migrations.AddConstraint(
            model_name="routestep",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ONGOING")),
                fields=("route",),
                name="only_one_ongoing_step_per_route",
            ),
        ),
    ]
