# Generated by Django 4.2.13 on 2024-07-10 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("turtlemail", "0019_route_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Datetime"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("N", "new"), ("R", "received")],
                        default="N",
                        max_length=2,
                        verbose_name="Status",
                    ),
                ),
                (
                    "route_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="turtlemail.routestep",
                        verbose_name="RouteStep context",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat message",
                "verbose_name_plural": "Chat messages",
                "ordering": ["route_step", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemChatMessage",
            fields=[
                (
                    "chatmessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="turtlemail.chatmessage",
                    ),
                ),
                (
                    "message_type",
                    models.IntegerField(
                        choices=[
                            (
                                1,
                                "\n                        Hello,<br />\n                        this chat was created for you to agree on the details of a package handover.\n                        Be excellent and careful with personal data.<br />\n                        Handover is planed on {date} and location {location}.<br />\n                        Happy turtlemailing!\n                                 ",
                            )
                        ],
                        verbose_name="Identifier of predefined system messages",
                    ),
                ),
                (
                    "content_data",
                    models.TextField(verbose_name="System message data context"),
                ),
            ],
            bases=("turtlemail.chatmessage",),
        ),
        migrations.CreateModel(
            name="UserChatMessage",
            fields=[
                (
                    "chatmessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="turtlemail.chatmessage",
                    ),
                ),
                ("content", models.TextField(verbose_name="Message content")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Message author",
                    ),
                ),
            ],
            bases=("turtlemail.chatmessage",),
        ),
    ]
