# Generated by Django 4.2.13 on 2024-07-31 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_user_settings(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    User = apps.get_model("turtlemail", "User")
    UserSettings = apps.get_model("turtlemail", "UserSettings")
    for user in User.objects.using(db_alias).all():
        user_settings = UserSettings(user=user)
        user_settings.save()


class Migration(migrations.Migration):
    dependencies = [
        ("turtlemail", "0020_chatmessage_systemchatmessage_userchatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="status",
            field=models.CharField(
                choices=[("N", "new"), ("NO", "notified"), ("R", "received")],
                default="N",
                max_length=2,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="systemchatmessage",
            name="message_type",
            field=models.IntegerField(
                choices=[
                    (
                        1,
                        "\n                        Hello,<br />\n                        this chat was created for you to agree on the details of a delivery handover.\n                        Be excellent and careful with personal data.<br />\n                        Handover is planned on {date} near {location}.<br />\n                        Happy turtlemailing!\n                                 ",
                    )
                ],
                verbose_name="Identifier of predefined system messages",
            ),
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wants_email_notifications_chat", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_user_settings),
    ]
