# Generated by Django 4.2.13 on 2024-08-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("turtlemail", "0021_alter_chatmessage_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="wants_email_notifications_requests",
            field=models.BooleanField(default=True),
        ),
    ]
