# Generated by Django 4.2.13 on 2024-08-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("turtlemail", "0022_usersettings_wants_email_notifications_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="routestep",
            name="notified_at",
            field=models.DateTimeField(
                null=True, verbose_name="Last notification sent"
            ),
        ),
    ]
