# Generated by Django 4.2.13 on 2024-09-19 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("turtlemail", "0023_routestep_notified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverylog",
            name="route",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="turtlemail.route",
                verbose_name="Route",
            ),
        ),
        migrations.AlterField(
            model_name="deliverylog",
            name="route_step",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_logs",
                to="turtlemail.routestep",
                verbose_name="Route Step",
            ),
        ),
        migrations.AlterField(
            model_name="packet",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_packets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Recipient",
            ),
        ),
        migrations.AlterField(
            model_name="packet",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_packets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sender",
            ),
        ),
    ]
