# Generated by Django 4.2.13 on 2024-09-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "turtlemail",
            "0024_alter_deliverylog_route_alter_deliverylog_route_step_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="packet",
            name="is_cancelled",
            field=models.BooleanField(default=False, verbose_name="Cancelled"),
        ),
    ]
